version: "3.3"
services:
  node-exporter:
    # image: prom/node-exporter:latest
    image: quay.io/prometheus/node-exporter:latest
    network_mode: "host"
    pid: host
    hostname: Monitor
    container_name: node-exporter
    volumes:
      # - /proc:/host/proc:ro
      # - /sys:/host/sys:ro
      # - /:/rootfs:ro
      - "/:/host:ro,rslave"
    command:
      # - "--path.procfs=/host/proc"
      # - "--path.rootfs=/rootfs"
      # - "--path.sysfs=/host/sys"
      # - --collector.filesystem.ignored-mount-points
      # - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
      - "--path.rootfs=/host"
    restart: unless-stopped
    #ports:
    #  - "192.168.1.34:9100:9100/tcp"
    #networks:
    #  - monitor-net
networks:
  monitor-net:
    driver: bridge
