global:
  smtp_smarthost: "smtp.gmail.com:587"
  smtp_from: "bivandat12a6.dqh@gmail.com"
  smtp_auth_username: "bivandat12a6.dqh@gmail.com"
  smtp_auth_identity: "bivandat12a6.dqh@gmail.com"
  smtp_auth_password: "bivandat24112001"
  resolve_timeout: 3m

templates:
  - "/etc/alertmanager/template/*.tmpl"

route:
  group_by: ["alertname"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: email

  routes:
    - matchers:
        - notify="email"
      receiver: email


inhibit_rules:
  - source_matchers: [severity="critical"]
    target_matchers: [severity="warning"]
    equal: [alertname]

receivers:
  - name: "email"
    email_configs:
      - to: "bivandat24112001@gmail.com"
        send_resolved: true